---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: restaurant
type: Opaque
stringData:
  DB_USER: postgres.iyhxwysdtwqcmmmpsial
  DB_HOST: aws-1-ap-south-1.pooler.supabase.com
  DB_PASSWORD: 'vfY#hEy*tn4_gGj'
  DB_NAME: postgres
  DB_PORT: '6543'
