{{- if .Values.initDatabase.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-initdb
  labels:
    {{- include "restaurant.labels" . | nindent 4 }}
data:
  init.sql: |-
{{ .Files.Get "sql/init.sql" | indent 4 }}
{{- end }}
