apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  labels:
    {{- include "restaurant.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.supabase.user }}
  DB_HOST: {{ .Values.supabase.host }}
  DB_PASSWORD: {{ .Values.supabase.password }}
  DB_NAME: {{ .Values.supabase.database }}
  DB_PORT: "{{ .Values.supabase.port }}"
