apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    {{- include "restaurant.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.serviceType }}
  selector:
    {{- include "restaurant.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
      {{- if eq .Values.backend.serviceType "NodePort" }}
      nodePort: {{ .Values.backend.nodePort }}
      {{- end }}
      protocol: TCP
